// Guards the ESM wrapper generated by script/build-esm.js.
// Usage (after `yarn build`): node tests/esm.test.mjs
import { createRequire } from 'module'
import assert from 'assert'
import localeCodes from '../dist/index.mjs'
import {
	all,
	where,
	whereAll,
	getByName,
	getByNameLocal,
	getByLocation,
	getByTag,
	getByLCID,
	getByISO6392,
	getByISO6391,
	getAllByName,
	getAllByNameLocal,
	getAllByLocation,
	getAllByTag,
	getAllByLCID,
	getAllByISO6392,
	getAllByISO6391
} from '../dist/index.mjs'

const require = createRequire(import.meta.url)
const commonjs = require('../dist/index.js')

// Resolving by package name (self-reference) is the only way to exercise the
// "exports" map in package.json - importing ../dist/index.mjs bypasses it.
const byPackageName = await import('locale-codes')
const requiredByPackageName = require('locale-codes')
assert.equal(byPackageName.default, commonjs, 'import "locale-codes" must resolve through "exports" to the same object')
assert.equal(requiredByPackageName, commonjs, 'require("locale-codes") must resolve through "exports" to the same object')
assert.deepEqual(
	Object.keys(byPackageName).filter(name => name !== 'default').sort(),
	Object.keys(commonjs).slice().sort(),
	'the ESM entry point must expose one named export per API member'
)

// The default export is the very same object served to require()
assert.equal(localeCodes, commonjs)
assert.equal(localeCodes.default, undefined)
assert.equal(all, commonjs.all)

// Every member of the CommonJS API is also a named export
const namedExports = {
	all,
	where,
	whereAll,
	getByName,
	getByNameLocal,
	getByLocation,
	getByTag,
	getByLCID,
	getByISO6392,
	getByISO6391,
	getAllByName,
	getAllByNameLocal,
	getAllByLocation,
	getAllByTag,
	getAllByLCID,
	getAllByISO6392,
	getAllByISO6391
}
assert.deepEqual(Object.keys(namedExports), Object.keys(commonjs))
Object.keys(namedExports).forEach(name => {
	assert.equal(namedExports[name], commonjs[name], `${name} must be re-exported by the ESM wrapper`)
})

// Named exports behave exactly like the methods of the default export
assert.equal(getByTag('pt-br').name, 'Portuguese')
assert.equal(getByTag('pt-br'), localeCodes.getByTag('pt-br'))
assert.equal(Array.isArray(getByISO6391('en')), false)
assert.equal(getAllByISO6391('en').length > 100, true)
assert.equal(where('tag', 'pt-br'), whereAll('tag', 'pt-br')[0])
assert.equal(all.length, commonjs.all.length)

console.log('Done!')
