// Generates the ESM wrapper published next to the CommonJS build.
// Usage (after `tsc`): node script/build-esm.js
//
// The CommonJS build in dist/index.js is never touched, so
// `require('locale-codes')` keeps returning the module object itself.
// dist/index.mjs simply re-exports that object as the default export plus one
// named export per API member, and dist/index.d.mts describes it.
const fs = require('fs')
const path = require('path')

const distributionPath = path.join(__dirname, '..', 'dist')
const localeCodes = require(path.join(distributionPath, 'index.js'))

// Derived from the built module so the wrapper can never drift from the API
const names = Object.keys(localeCodes)

const banner = [
	'// Generated by script/build-esm.js - do not edit.',
	'// ESM wrapper around the CommonJS build in ./index.js'
]

const source = [
	...banner,
	'',
	"import localeCodes from './index.js'",
	'',
	...names.map(name => `export const ${name} = localeCodes.${name}`),
	'',
	'export default localeCodes',
	''
].join('\n')

const types = [
	...banner,
	'',
	"import type { ILocale, LocaleCodes } from './types.js'",
	'',
	'declare const localeCodes: LocaleCodes;',
	'',
	...names.map(name => `export declare const ${name}: LocaleCodes['${name}'];`),
	'',
	'export type { ILocale, LocaleCodes };',
	'export default localeCodes;',
	''
].join('\n')

fs.writeFileSync(path.join(distributionPath, 'index.mjs'), source)
fs.writeFileSync(path.join(distributionPath, 'index.d.mts'), types)

console.log(`Generated dist/index.mjs and dist/index.d.mts (${names.length} named exports)`)
